server:
  port: 8080
  servlet:
    context-path: /phoenix

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.com.starlight.*.model
  global-config:
    #数据库相关配置
    db-config:
      #主键类型
      id-type: AUTO
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
#    sql语句是否打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

spring:
  profiles:
    active: db
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  config: classpath:log4j2.xml
